name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Add ZNC PPA
      run: sudo add-apt-repository -y ppa:teward/znc
    - name: Update apt cache
      run: sudo apt -qq update
    - name: Install build dependencies
      run: sudo apt install -y znc znc-dev libcurl4-openssl-dev
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
